# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/subhashis/programming/VR/Qtcreator/GPUPBVR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/subhashis/programming/VR/Qtcreator/GPUPBVR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/subhashis/programming/VR/Qtcreator/GPUPBVR/CMakeFiles /home/subhashis/programming/VR/Qtcreator/GPUPBVR/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/subhashis/programming/VR/Qtcreator/GPUPBVR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PBVR

# Build rule for target.
PBVR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PBVR
.PHONY : PBVR

# fast build rule for target.
PBVR/fast:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/build
.PHONY : PBVR/fast

CudaRenderer.o: CudaRenderer.cpp.o
.PHONY : CudaRenderer.o

# target to build an object file
CudaRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/CudaRenderer.cpp.o
.PHONY : CudaRenderer.cpp.o

CudaRenderer.i: CudaRenderer.cpp.i
.PHONY : CudaRenderer.i

# target to preprocess a source file
CudaRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/CudaRenderer.cpp.i
.PHONY : CudaRenderer.cpp.i

CudaRenderer.s: CudaRenderer.cpp.s
.PHONY : CudaRenderer.s

# target to generate assembly for a file
CudaRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/CudaRenderer.cpp.s
.PHONY : CudaRenderer.cpp.s

PerlinNoise.o: PerlinNoise.cpp.o
.PHONY : PerlinNoise.o

# target to build an object file
PerlinNoise.cpp.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/PerlinNoise.cpp.o
.PHONY : PerlinNoise.cpp.o

PerlinNoise.i: PerlinNoise.cpp.i
.PHONY : PerlinNoise.i

# target to preprocess a source file
PerlinNoise.cpp.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/PerlinNoise.cpp.i
.PHONY : PerlinNoise.cpp.i

PerlinNoise.s: PerlinNoise.cpp.s
.PHONY : PerlinNoise.s

# target to generate assembly for a file
PerlinNoise.cpp.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/PerlinNoise.cpp.s
.PHONY : PerlinNoise.cpp.s

SGrid.o: SGrid.cpp.o
.PHONY : SGrid.o

# target to build an object file
SGrid.cpp.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/SGrid.cpp.o
.PHONY : SGrid.cpp.o

SGrid.i: SGrid.cpp.i
.PHONY : SGrid.i

# target to preprocess a source file
SGrid.cpp.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/SGrid.cpp.i
.PHONY : SGrid.cpp.i

SGrid.s: SGrid.cpp.s
.PHONY : SGrid.s

# target to generate assembly for a file
SGrid.cpp.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/SGrid.cpp.s
.PHONY : SGrid.cpp.s

Singleton.o: Singleton.cpp.o
.PHONY : Singleton.o

# target to build an object file
Singleton.cpp.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/Singleton.cpp.o
.PHONY : Singleton.cpp.o

Singleton.i: Singleton.cpp.i
.PHONY : Singleton.i

# target to preprocess a source file
Singleton.cpp.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/Singleton.cpp.i
.PHONY : Singleton.cpp.i

Singleton.s: Singleton.cpp.s
.PHONY : Singleton.s

# target to generate assembly for a file
Singleton.cpp.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/Singleton.cpp.s
.PHONY : Singleton.cpp.s

UGridTetrahedrizer.o: UGridTetrahedrizer.cpp.o
.PHONY : UGridTetrahedrizer.o

# target to build an object file
UGridTetrahedrizer.cpp.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/UGridTetrahedrizer.cpp.o
.PHONY : UGridTetrahedrizer.cpp.o

UGridTetrahedrizer.i: UGridTetrahedrizer.cpp.i
.PHONY : UGridTetrahedrizer.i

# target to preprocess a source file
UGridTetrahedrizer.cpp.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/UGridTetrahedrizer.cpp.i
.PHONY : UGridTetrahedrizer.cpp.i

UGridTetrahedrizer.s: UGridTetrahedrizer.cpp.s
.PHONY : UGridTetrahedrizer.s

# target to generate assembly for a file
UGridTetrahedrizer.cpp.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/UGridTetrahedrizer.cpp.s
.PHONY : UGridTetrahedrizer.cpp.s

VBOCreator.o: VBOCreator.cpp.o
.PHONY : VBOCreator.o

# target to build an object file
VBOCreator.cpp.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/VBOCreator.cpp.o
.PHONY : VBOCreator.cpp.o

VBOCreator.i: VBOCreator.cpp.i
.PHONY : VBOCreator.i

# target to preprocess a source file
VBOCreator.cpp.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/VBOCreator.cpp.i
.PHONY : VBOCreator.cpp.i

VBOCreator.s: VBOCreator.cpp.s
.PHONY : VBOCreator.s

# target to generate assembly for a file
VBOCreator.cpp.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/VBOCreator.cpp.s
.PHONY : VBOCreator.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/main.cpp.s
.PHONY : main.cpp.s

moc_CudaRenderer.o: moc_CudaRenderer.cxx.o
.PHONY : moc_CudaRenderer.o

# target to build an object file
moc_CudaRenderer.cxx.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_CudaRenderer.cxx.o
.PHONY : moc_CudaRenderer.cxx.o

moc_CudaRenderer.i: moc_CudaRenderer.cxx.i
.PHONY : moc_CudaRenderer.i

# target to preprocess a source file
moc_CudaRenderer.cxx.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_CudaRenderer.cxx.i
.PHONY : moc_CudaRenderer.cxx.i

moc_CudaRenderer.s: moc_CudaRenderer.cxx.s
.PHONY : moc_CudaRenderer.s

# target to generate assembly for a file
moc_CudaRenderer.cxx.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_CudaRenderer.cxx.s
.PHONY : moc_CudaRenderer.cxx.s

moc_PerlinNoise.o: moc_PerlinNoise.cxx.o
.PHONY : moc_PerlinNoise.o

# target to build an object file
moc_PerlinNoise.cxx.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_PerlinNoise.cxx.o
.PHONY : moc_PerlinNoise.cxx.o

moc_PerlinNoise.i: moc_PerlinNoise.cxx.i
.PHONY : moc_PerlinNoise.i

# target to preprocess a source file
moc_PerlinNoise.cxx.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_PerlinNoise.cxx.i
.PHONY : moc_PerlinNoise.cxx.i

moc_PerlinNoise.s: moc_PerlinNoise.cxx.s
.PHONY : moc_PerlinNoise.s

# target to generate assembly for a file
moc_PerlinNoise.cxx.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_PerlinNoise.cxx.s
.PHONY : moc_PerlinNoise.cxx.s

moc_SGrid.o: moc_SGrid.cxx.o
.PHONY : moc_SGrid.o

# target to build an object file
moc_SGrid.cxx.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_SGrid.cxx.o
.PHONY : moc_SGrid.cxx.o

moc_SGrid.i: moc_SGrid.cxx.i
.PHONY : moc_SGrid.i

# target to preprocess a source file
moc_SGrid.cxx.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_SGrid.cxx.i
.PHONY : moc_SGrid.cxx.i

moc_SGrid.s: moc_SGrid.cxx.s
.PHONY : moc_SGrid.s

# target to generate assembly for a file
moc_SGrid.cxx.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_SGrid.cxx.s
.PHONY : moc_SGrid.cxx.s

moc_Singleton.o: moc_Singleton.cxx.o
.PHONY : moc_Singleton.o

# target to build an object file
moc_Singleton.cxx.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_Singleton.cxx.o
.PHONY : moc_Singleton.cxx.o

moc_Singleton.i: moc_Singleton.cxx.i
.PHONY : moc_Singleton.i

# target to preprocess a source file
moc_Singleton.cxx.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_Singleton.cxx.i
.PHONY : moc_Singleton.cxx.i

moc_Singleton.s: moc_Singleton.cxx.s
.PHONY : moc_Singleton.s

# target to generate assembly for a file
moc_Singleton.cxx.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_Singleton.cxx.s
.PHONY : moc_Singleton.cxx.s

moc_UGridTetrahedrizer.o: moc_UGridTetrahedrizer.cxx.o
.PHONY : moc_UGridTetrahedrizer.o

# target to build an object file
moc_UGridTetrahedrizer.cxx.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_UGridTetrahedrizer.cxx.o
.PHONY : moc_UGridTetrahedrizer.cxx.o

moc_UGridTetrahedrizer.i: moc_UGridTetrahedrizer.cxx.i
.PHONY : moc_UGridTetrahedrizer.i

# target to preprocess a source file
moc_UGridTetrahedrizer.cxx.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_UGridTetrahedrizer.cxx.i
.PHONY : moc_UGridTetrahedrizer.cxx.i

moc_UGridTetrahedrizer.s: moc_UGridTetrahedrizer.cxx.s
.PHONY : moc_UGridTetrahedrizer.s

# target to generate assembly for a file
moc_UGridTetrahedrizer.cxx.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_UGridTetrahedrizer.cxx.s
.PHONY : moc_UGridTetrahedrizer.cxx.s

moc_VBOCreator.o: moc_VBOCreator.cxx.o
.PHONY : moc_VBOCreator.o

# target to build an object file
moc_VBOCreator.cxx.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_VBOCreator.cxx.o
.PHONY : moc_VBOCreator.cxx.o

moc_VBOCreator.i: moc_VBOCreator.cxx.i
.PHONY : moc_VBOCreator.i

# target to preprocess a source file
moc_VBOCreator.cxx.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_VBOCreator.cxx.i
.PHONY : moc_VBOCreator.cxx.i

moc_VBOCreator.s: moc_VBOCreator.cxx.s
.PHONY : moc_VBOCreator.s

# target to generate assembly for a file
moc_VBOCreator.cxx.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_VBOCreator.cxx.s
.PHONY : moc_VBOCreator.cxx.s

moc_defs.o: moc_defs.cxx.o
.PHONY : moc_defs.o

# target to build an object file
moc_defs.cxx.o:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_defs.cxx.o
.PHONY : moc_defs.cxx.o

moc_defs.i: moc_defs.cxx.i
.PHONY : moc_defs.i

# target to preprocess a source file
moc_defs.cxx.i:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_defs.cxx.i
.PHONY : moc_defs.cxx.i

moc_defs.s: moc_defs.cxx.s
.PHONY : moc_defs.s

# target to generate assembly for a file
moc_defs.cxx.s:
	$(MAKE) -f CMakeFiles/PBVR.dir/build.make CMakeFiles/PBVR.dir/moc_defs.cxx.s
.PHONY : moc_defs.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PBVR"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CudaRenderer.o"
	@echo "... CudaRenderer.i"
	@echo "... CudaRenderer.s"
	@echo "... PerlinNoise.o"
	@echo "... PerlinNoise.i"
	@echo "... PerlinNoise.s"
	@echo "... SGrid.o"
	@echo "... SGrid.i"
	@echo "... SGrid.s"
	@echo "... Singleton.o"
	@echo "... Singleton.i"
	@echo "... Singleton.s"
	@echo "... UGridTetrahedrizer.o"
	@echo "... UGridTetrahedrizer.i"
	@echo "... UGridTetrahedrizer.s"
	@echo "... VBOCreator.o"
	@echo "... VBOCreator.i"
	@echo "... VBOCreator.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moc_CudaRenderer.o"
	@echo "... moc_CudaRenderer.i"
	@echo "... moc_CudaRenderer.s"
	@echo "... moc_PerlinNoise.o"
	@echo "... moc_PerlinNoise.i"
	@echo "... moc_PerlinNoise.s"
	@echo "... moc_SGrid.o"
	@echo "... moc_SGrid.i"
	@echo "... moc_SGrid.s"
	@echo "... moc_Singleton.o"
	@echo "... moc_Singleton.i"
	@echo "... moc_Singleton.s"
	@echo "... moc_UGridTetrahedrizer.o"
	@echo "... moc_UGridTetrahedrizer.i"
	@echo "... moc_UGridTetrahedrizer.s"
	@echo "... moc_VBOCreator.o"
	@echo "... moc_VBOCreator.i"
	@echo "... moc_VBOCreator.s"
	@echo "... moc_defs.o"
	@echo "... moc_defs.i"
	@echo "... moc_defs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

